### ISSUE TITLE
Internal server error while listing organizations

### ISSUE THREAD

**Issue by madurangasiriwardena** [wso2-extensions/identity-organization-management#22]
**Description:**

- Create a setup with MySQL as the database
- Create a tenant type organization
- List the organizations. Internal server error is returned. Below stacktrace is printed in the backend.

```
[2022-04-27 08:57:53,044] [126c9b7f-4463-4ea7-bb15-5e698ca67024] ERROR {org.wso2.carbon.identity.organization.management.endpoint.service.OrganizationManagementService} - errorCode: ORG-65002 | message: Server encountered an error while retrieving the organizations in tenant: carbon.super org.wso2.carbon.identity.organization.management.service.exception.OrganizationManagementServerException: Unable to retrieve the organizations.
	at org.wso2.carbon.identity.organization.management.service.util.Utils.handleServerException(Utils.java:77)
	at org.wso2.carbon.identity.organization.management.service.dao.impl.OrganizationManagementDAOImpl.getOrganizations(OrganizationManagementDAOImpl.java:325)
	at org.wso2.carbon.identity.organization.management.service.dao.impl.CachedBackedOrganizationManagementDAO.getOrganizations(CachedBackedOrganizationManagementDAO.java:131)
	at org.wso2.carbon.identity.organization.management.service.OrganizationManagerImpl.getOrganizations(OrganizationManagerImpl.java:224)
	at org.wso2.carbon.identity.organization.management.endpoint.service.OrganizationManagementService.getOrganizations(OrganizationManagementService.java:100)
	at org.wso2.carbon.identity.organization.management.endpoint.impl.OrganizationsApiServiceImpl.organizationsGet(OrganizationsApiServiceImpl.java:43)
	at org.wso2.carbon.identity.organization.management.endpoint.OrganizationsApi.organizationsGet(OrganizationsApi.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:201)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:104)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:265)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:225)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:304)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:222)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:279)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:385)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:313)
	at org.wso2.carbon.identity.context.rewrite.valve.TenantContextRewriteValve.invoke(TenantContextRewriteValve.java:145)
	at org.wso2.carbon.tomcat.ext.valves.SameSiteCookieValve.invoke(SameSiteCookieValve.java:38)
	at org.wso2.carbon.identity.cors.valve.CORSValve.invoke(CORSValve.java:89)
	at org.wso2.carbon.identity.authz.valve.AuthorizationValve.invoke(AuthorizationValve.java:106)
	at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:144)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:106)
	at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:49)
	at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:67)
	at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:145)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:61)
	at org.wso2.carbon.tomcat.ext.valves.RequestEncodingValve.invoke(RequestEncodingValve.java:49)
	at org.wso2.carbon.tomcat.ext.valves.RequestCorrelationIdValve.invoke(RequestCorrelationIdValve.java:137)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1735)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.wso2.carbon.database.utils.jdbc.exceptions.DataAccessException: Error in performing Database query: '%s' SELECT UM_ORG.UM_ID, UM_ORG.UM_ORG_NAME, UM_ORG.UM_CREATED_TIME FROM UM_ORG INNER JOIN UM_USER_ROLE_ORG ON UM_USER_ROLE_ORG.ORG_ID = UM_ORG.UM_ID WHERE UM_USER_ROLE_ORG.UM_USER_ID = :USER_ID; AND UM_USER_ROLE_ORG.UM_TENANT_ID = :TENANT_ID; AND UM_HYBRID_ROLE_ID IN (SELECT UM_ID FROM UM_HYBRID_ROLE WHERE UM_ROLE_NAME IN (SELECT UM_ROLE_NAME FROM UM_ROLE_PERMISSION WHERE UM_PERMISSION_ID IN (SELECT UM_ID FROM UM_PERMISSION WHERE UM_RESOURCE_ID IN (:PERMISSION_1;, :PERMISSION_2;, :PERMISSION_3;, :PERMISSION_4;, :PERMISSION_5;, :PERMISSION_6;)))) AND UM_ORG.UM_TENANT_ID = :TENANT_ID; ORDER BY UM_ORG.UM_CREATED_TIME DESC LIMIT :LIMIT;
	at org.wso2.carbon.database.utils.jdbc.NamedJdbcTemplate.executeQuery(NamedJdbcTemplate.java:169)
	at org.wso2.carbon.identity.organization.management.service.dao.impl.OrganizationManagementDAOImpl.getOrganizations(OrganizationManagementDAOImpl.java:303)
	... 59 more
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'UM_HYBRID_ROLE_ID' in 'IN/ALL/ANY subquery'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009)
	at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:118)
	at com.sun.proxy.$Proxy50.executeQuery(Unknown Source)
	at org.wso2.carbon.database.utils.jdbc.NamedPreparedStatement.executeQuery(NamedPreparedStatement.java:246)
	at org.wso2.carbon.database.utils.jdbc.NamedJdbcTemplate.executeQuery(NamedJdbcTemplate.java:154)
	... 60 more
```

**Comment by dewniMW** [comment]
This can be resolved by using the following query when creating the table:

```
CREATE TABLE UM_USER_ROLE_ORG (
    UM_ID VARCHAR(255) NOT NULL,
    UM_USER_ID VARCHAR(255) NOT NULL,
    UM_ROLE_ID VARCHAR(1024) NOT NULL,
    UM_HYBRID_ROLE_ID INTEGER NOT NULL,
    UM_TENANT_ID INTEGER DEFAULT 0,
    ORG_ID VARCHAR(255) NOT NULL,
    ASSIGNED_AT VARCHAR(255) NOT NULL,
    MANDATORY INTEGER DEFAULT 0,
    PRIMARY KEY (UM_ID),
    CONSTRAINT UM_USER_ROLE_ORG_CONSTRAINT UNIQUE(UM_USER_ID, UM_HYBRID_ROLE_ID, UM_TENANT_ID, ORG_ID, ASSIGNED_AT),
    CONSTRAINT FK_UM_USER_ROLE_ORG_UM_HYBRID_ROLE FOREIGN KEY (UM_HYBRID_ROLE_ID, UM_TENANT_ID) REFERENCES UM_HYBRID_ROLE(UM_ID, UM_TENANT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_UM_USER_ROLE_ORG_UM_ORG FOREIGN KEY (ORG_ID) REFERENCES UM_ORG(UM_ID) ON DELETE CASCADE,
    CONSTRAINT FK_UM_USER_ROLE_ORG_ASSIGNED_AT FOREIGN KEY (ASSIGNED_AT) REFERENCES UM_ORG(UM_ID) ON DELETE CASCADE
);
```
